// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function BancloneLogin(arg1:string,arg2:string):Promise<string>;

export function CheckCloneHVStock(arg1:string,arg2:string,arg3:string):Promise<app.CloneHVStockResult>;

export function CheckCurrentIPViaProxy():Promise<string>;

export function ClearUploadLog():Promise<void>;

export function CloneProfile(arg1:string):Promise<string>;

export function CreateProfile(arg1:string):Promise<string>;

export function DebugMemory():Promise<Record<string, any>>;

export function DeleteAccounts(arg1:Array<number>):Promise<app.DeleteResult>;

export function DeleteProfile(arg1:string):Promise<string>;

export function EmitQuitConfirm():Promise<void>;

export function ExportFbVersionPool(arg1:string,arg2:Array<string>):Promise<string>;

export function FetchMailHVDomains(arg1:string):Promise<string>;

export function FetchStore1sProducts(arg1:string):Promise<string>;

export function FetchVietXFDomains(arg1:string):Promise<string>;

export function FetchWeMakeMailDomains(arg1:string):Promise<string>;

export function ForceMemoryCleanup():Promise<Record<string, any>>;

export function GetAccount(arg1:number):Promise<app.Account>;

export function GetAccountSourceFolder():Promise<string>;

export function GetActiveProfileID():Promise<string>;

export function GetAppVersion():Promise<string>;

export function GetBancloneProducts(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetBuildUARegStats():Promise<Array<app.RegStatRow>>;

export function GetBuildUAVerStats():Promise<Array<app.RegStatRow>>;

export function GetCookieInitialStatus(arg1:string):Promise<Record<string, any>>;

export function GetDatrPoolSize():Promise<number>;

export function GetDefaultCookiePaths():Promise<Record<string, string>>;

export function GetDefaultResultPath():Promise<string>;

export function GetDefaultUAContent(arg1:string):Promise<string>;

export function GetDefaultUACounts():Promise<Record<string, number>>;

export function GetFbAppStatus():Promise<app.FbAppStatus>;

export function GetFbVersionMap():Promise<Record<string, string>>;

export function GetMailDomainStats():Promise<Array<app.MailDomainStatRow>>;

export function GetPermanentFileCounts():Promise<Record<string, number>>;

export function GetPhoneCountries():Promise<Array<app.PhoneCountryInfo>>;

export function GetPoolFileSaveCount():Promise<number>;

export function GetRegStats():Promise<Array<app.RegStatRow>>;

export function GetResourceUsage():Promise<app.AppResourceUsage>;

export function GetRunStatus():Promise<Record<string, boolean>>;

export function GetUAPoolsStatus():Promise<Array<app.UAPoolStatus>>;

export function GetUploadStats():Promise<app.UploadStats>;

export function GetVerifyStats():Promise<Array<app.RegStatRow>>;

export function ImportAccounts(arg1:string):Promise<app.ImportResult>;

export function ImportLegacyConfig(arg1:string,arg2:string):Promise<string>;

export function InvalidateProxyCache():Promise<void>;

export function IsConfirmedQuit():Promise<boolean>;

export function IsRegisterRunning():Promise<boolean>;

export function IsRegisterStopping():Promise<boolean>;

export function IsVerifyRunning():Promise<boolean>;

export function IsVerifyStopping():Promise<boolean>;

export function ListAccounts(arg1:app.AccountFilter):Promise<app.AccountListResult>;

export function ListProfiles():Promise<Array<app.ProfileInfo>>;

export function LoadAccountsFromFile(arg1:string):Promise<app.ImportResult>;

export function LoadInteractionConfig():Promise<app.InteractionConfig>;

export function LoadProxyList(arg1:string):Promise<string>;

export function LoadSettings():Promise<app.SettingsData>;

export function LoadUploadSiteConfig():Promise<app.UploadSiteConfig>;

export function LookupPhoneCountry(arg1:string):Promise<app.PhoneCountryInfo>;

export function NotifyVisibilityChange(arg1:boolean):Promise<void>;

export function OnSecondInstance():Promise<void>;

export function OpenConfigFolder():Promise<string>;

export function OpenCookieInitialFile(arg1:string):Promise<string>;

export function OpenFileDialogPath():Promise<string>;

export function OpenFolderDialog():Promise<string>;

export function OpenFolderInExplorer(arg1:string):Promise<string>;

export function OpenTextFileDialog():Promise<string>;

export function OpenUAFileInEditor(arg1:string):Promise<string>;

export function OpenVersionsAndBuildsFile(arg1:string):Promise<string>;

export function ParseLegacyConfig(arg1:string,arg2:string):Promise<app.LegacyParseResult>;

export function ReadTextFile(arg1:string):Promise<string>;

export function RefreshAccountSource():Promise<app.ImportResult>;

export function RegisterFacebook(arg1:app.RegisterInput):Promise<string>;

export function ReloadFbAppVersions():Promise<number>;

export function RenameProfile(arg1:string,arg2:string):Promise<string>;

export function RequestQuit():Promise<void>;

export function ResetUploadSession():Promise<void>;

export function RunRegister(arg1:number):Promise<string>;

export function RunVerify(arg1:app.VerifyRunConfig):Promise<string>;

export function SaveFbAppVersions(arg1:string):Promise<string>;

export function SaveInteractionConfig(arg1:app.InteractionConfig):Promise<string>;

export function SaveProxyList(arg1:string,arg2:string):Promise<string>;

export function SaveSettings(arg1:app.SettingsData):Promise<string>;

export function SaveUAPool(arg1:string,arg2:string):Promise<string>;

export function SaveUploadSiteConfig(arg1:app.UploadSiteConfig):Promise<string>;

export function SetAccountSourceFolder(arg1:string):Promise<app.ImportResult>;

export function SetActiveProfile(arg1:string):Promise<string>;

export function SetVersion(arg1:string):Promise<void>;

export function SimulatePlatformUA(arg1:string,arg2:app.PlatformUAConfig):Promise<string>;

export function StartUploadSite():Promise<string>;

export function StopRegister():Promise<string>;

export function StopUploadSite():Promise<void>;

export function StopVerify():Promise<string>;

export function ValidateFilePath(arg1:string):Promise<string>;

export function ValidatePath(arg1:string):Promise<string>;
