// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BancloneLogin(arg1, arg2) {
  return window['go']['main']['App']['BancloneLogin'](arg1, arg2);
}

export function CheckCloneHVStock(arg1, arg2, arg3) {
  return window['go']['main']['App']['CheckCloneHVStock'](arg1, arg2, arg3);
}

export function CheckCurrentIPViaProxy() {
  return window['go']['main']['App']['CheckCurrentIPViaProxy']();
}

export function ClearUploadLog() {
  return window['go']['main']['App']['ClearUploadLog']();
}

export function CloneProfile(arg1) {
  return window['go']['main']['App']['CloneProfile'](arg1);
}

export function CreateProfile(arg1) {
  return window['go']['main']['App']['CreateProfile'](arg1);
}

export function DebugMemory() {
  return window['go']['main']['App']['DebugMemory']();
}

export function DeleteAccounts(arg1) {
  return window['go']['main']['App']['DeleteAccounts'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function EmitQuitConfirm() {
  return window['go']['main']['App']['EmitQuitConfirm']();
}

export function ExportFbVersionPool(arg1, arg2) {
  return window['go']['main']['App']['ExportFbVersionPool'](arg1, arg2);
}

export function FetchMailHVDomains(arg1) {
  return window['go']['main']['App']['FetchMailHVDomains'](arg1);
}

export function FetchStore1sProducts(arg1) {
  return window['go']['main']['App']['FetchStore1sProducts'](arg1);
}

export function FetchVietXFDomains(arg1) {
  return window['go']['main']['App']['FetchVietXFDomains'](arg1);
}

export function FetchWeMakeMailDomains(arg1) {
  return window['go']['main']['App']['FetchWeMakeMailDomains'](arg1);
}

export function ForceMemoryCleanup() {
  return window['go']['main']['App']['ForceMemoryCleanup']();
}

export function GetAccount(arg1) {
  return window['go']['main']['App']['GetAccount'](arg1);
}

export function GetAccountSourceFolder() {
  return window['go']['main']['App']['GetAccountSourceFolder']();
}

export function GetActiveProfileID() {
  return window['go']['main']['App']['GetActiveProfileID']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetBancloneProducts(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetBancloneProducts'](arg1, arg2, arg3);
}

export function GetBuildUARegStats() {
  return window['go']['main']['App']['GetBuildUARegStats']();
}

export function GetBuildUAVerStats() {
  return window['go']['main']['App']['GetBuildUAVerStats']();
}

export function GetCookieInitialStatus(arg1) {
  return window['go']['main']['App']['GetCookieInitialStatus'](arg1);
}

export function GetDatrPoolSize() {
  return window['go']['main']['App']['GetDatrPoolSize']();
}

export function GetDefaultCookiePaths() {
  return window['go']['main']['App']['GetDefaultCookiePaths']();
}

export function GetDefaultResultPath() {
  return window['go']['main']['App']['GetDefaultResultPath']();
}

export function GetDefaultUAContent(arg1) {
  return window['go']['main']['App']['GetDefaultUAContent'](arg1);
}

export function GetDefaultUACounts() {
  return window['go']['main']['App']['GetDefaultUACounts']();
}

export function GetFbAppStatus() {
  return window['go']['main']['App']['GetFbAppStatus']();
}

export function GetFbVersionMap() {
  return window['go']['main']['App']['GetFbVersionMap']();
}

export function GetMailDomainStats() {
  return window['go']['main']['App']['GetMailDomainStats']();
}

export function GetPermanentFileCounts() {
  return window['go']['main']['App']['GetPermanentFileCounts']();
}

export function GetPhoneCountries() {
  return window['go']['main']['App']['GetPhoneCountries']();
}

export function GetPoolFileSaveCount() {
  return window['go']['main']['App']['GetPoolFileSaveCount']();
}

export function GetRegStats() {
  return window['go']['main']['App']['GetRegStats']();
}

export function GetResourceUsage() {
  return window['go']['main']['App']['GetResourceUsage']();
}

export function GetRunStatus() {
  return window['go']['main']['App']['GetRunStatus']();
}

export function GetUAPoolsStatus() {
  return window['go']['main']['App']['GetUAPoolsStatus']();
}

export function GetUploadStats() {
  return window['go']['main']['App']['GetUploadStats']();
}

export function GetVerifyStats() {
  return window['go']['main']['App']['GetVerifyStats']();
}

export function ImportAccounts(arg1) {
  return window['go']['main']['App']['ImportAccounts'](arg1);
}

export function ImportLegacyConfig(arg1, arg2) {
  return window['go']['main']['App']['ImportLegacyConfig'](arg1, arg2);
}

export function InvalidateProxyCache() {
  return window['go']['main']['App']['InvalidateProxyCache']();
}

export function IsConfirmedQuit() {
  return window['go']['main']['App']['IsConfirmedQuit']();
}

export function IsRegisterRunning() {
  return window['go']['main']['App']['IsRegisterRunning']();
}

export function IsRegisterStopping() {
  return window['go']['main']['App']['IsRegisterStopping']();
}

export function IsVerifyRunning() {
  return window['go']['main']['App']['IsVerifyRunning']();
}

export function IsVerifyStopping() {
  return window['go']['main']['App']['IsVerifyStopping']();
}

export function ListAccounts(arg1) {
  return window['go']['main']['App']['ListAccounts'](arg1);
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function LoadAccountsFromFile(arg1) {
  return window['go']['main']['App']['LoadAccountsFromFile'](arg1);
}

export function LoadInteractionConfig() {
  return window['go']['main']['App']['LoadInteractionConfig']();
}

export function LoadProxyList(arg1) {
  return window['go']['main']['App']['LoadProxyList'](arg1);
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function LoadUploadSiteConfig() {
  return window['go']['main']['App']['LoadUploadSiteConfig']();
}

export function LookupPhoneCountry(arg1) {
  return window['go']['main']['App']['LookupPhoneCountry'](arg1);
}

export function NotifyVisibilityChange(arg1) {
  return window['go']['main']['App']['NotifyVisibilityChange'](arg1);
}

export function OpenConfigFolder() {
  return window['go']['main']['App']['OpenConfigFolder']();
}

export function OpenCookieInitialFile(arg1) {
  return window['go']['main']['App']['OpenCookieInitialFile'](arg1);
}

export function OpenFileDialogPath() {
  return window['go']['main']['App']['OpenFileDialogPath']();
}

export function OpenFolderDialog() {
  return window['go']['main']['App']['OpenFolderDialog']();
}

export function OpenFolderInExplorer(arg1) {
  return window['go']['main']['App']['OpenFolderInExplorer'](arg1);
}

export function OpenTextFileDialog() {
  return window['go']['main']['App']['OpenTextFileDialog']();
}

export function OpenUAFileInEditor(arg1) {
  return window['go']['main']['App']['OpenUAFileInEditor'](arg1);
}

export function OpenVersionsAndBuildsFile(arg1) {
  return window['go']['main']['App']['OpenVersionsAndBuildsFile'](arg1);
}

export function ParseLegacyConfig(arg1, arg2) {
  return window['go']['main']['App']['ParseLegacyConfig'](arg1, arg2);
}

export function ReadTextFile(arg1) {
  return window['go']['main']['App']['ReadTextFile'](arg1);
}

export function RefreshAccountSource() {
  return window['go']['main']['App']['RefreshAccountSource']();
}

export function RegisterFacebook(arg1) {
  return window['go']['main']['App']['RegisterFacebook'](arg1);
}

export function ReloadFbAppVersions() {
  return window['go']['main']['App']['ReloadFbAppVersions']();
}

export function RenameProfile(arg1, arg2) {
  return window['go']['main']['App']['RenameProfile'](arg1, arg2);
}

export function RequestQuit() {
  return window['go']['main']['App']['RequestQuit']();
}

export function ResetUploadSession() {
  return window['go']['main']['App']['ResetUploadSession']();
}

export function RunRegister(arg1) {
  return window['go']['main']['App']['RunRegister'](arg1);
}

export function RunVerify(arg1) {
  return window['go']['main']['App']['RunVerify'](arg1);
}

export function SaveFbAppVersions(arg1) {
  return window['go']['main']['App']['SaveFbAppVersions'](arg1);
}

export function SaveInteractionConfig(arg1) {
  return window['go']['main']['App']['SaveInteractionConfig'](arg1);
}

export function SaveProxyList(arg1, arg2) {
  return window['go']['main']['App']['SaveProxyList'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveUAPool(arg1, arg2) {
  return window['go']['main']['App']['SaveUAPool'](arg1, arg2);
}

export function SaveUploadSiteConfig(arg1) {
  return window['go']['main']['App']['SaveUploadSiteConfig'](arg1);
}

export function SetAccountSourceFolder(arg1) {
  return window['go']['main']['App']['SetAccountSourceFolder'](arg1);
}

export function SetActiveProfile(arg1) {
  return window['go']['main']['App']['SetActiveProfile'](arg1);
}

export function SimulatePlatformUA(arg1, arg2) {
  return window['go']['main']['App']['SimulatePlatformUA'](arg1, arg2);
}

export function StartUploadSite() {
  return window['go']['main']['App']['StartUploadSite']();
}

export function StopRegister() {
  return window['go']['main']['App']['StopRegister']();
}

export function StopUploadSite() {
  return window['go']['main']['App']['StopUploadSite']();
}

export function StopVerify() {
  return window['go']['main']['App']['StopVerify']();
}

export function ValidateFilePath(arg1) {
  return window['go']['main']['App']['ValidateFilePath'](arg1);
}

export function ValidatePath(arg1) {
  return window['go']['main']['App']['ValidatePath'](arg1);
}
